# Generated by Django 5.1 on 2024-08-08 15:58

from django.db import migrations


def copy_data(apps, schema_editor):
    Car = apps.get_model("demo", "Car")
    Manufacturer = apps.get_model("demo", "Manufacturer")

    for car in Car.objects.all():
        obj, _ = Manufacturer.objects.get_or_create(name=car.manufacturer)

        car.manufacturer_related = obj
        car.save()


def remove_data(apps, schema_editor):
    Car = apps.get_model("demo", "Car")
    Manufacturer = apps.get_model("demo", "Manufacturer")

    for car in Car.objects.all():
        car.manufacturer = car.manufacturer_related.name
        car.save()
    Manufacturer.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_manufacturer_car_manufacturer_related"),
    ]

    operations = [
        # migrations.RunPython(copy_data, reverse_code=migrations.RunPython.noop)
        migrations.RunPython(copy_data, reverse_code=remove_data)
    ]
